import "./globals.scss";
import Navbar from "@/components/Navbar/Navbar";
import Providers from "./providers";
import { Input } from "@nextui-org/react";
import "react-toastify/dist/ReactToastify.css";
import Footer from "@/components/footer/Footer";
import {Poppins} from 'next/font/google'

const poppins = Poppins({subsets: ['latin'], weight: "500"})

export const metadata = {
    title: "Emm's Computers",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={poppins.className}>
                <Providers>
                    <div className="min-h-screen w-full flex flex-col justify-between">
                        <Navbar />
                        {children}
                        <Footer />
                    </div>
                </Providers>
            </body>
        </html>
    );
}
